spring:
  application:
    name: ApiGateway1
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
          filters :
            - AuthenticationFilter
             
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**
          filters:
            - AuthenticationFilter
              
        - id: RATINGSERVICE1
          uri: lb://RATINGSERVICE-1
          predicates:
            - Path=/ratings/**
          filters:
            - AuthenticationFilter
              
        - id: SECURITY
          uri: lb://SECURITY
          predicates:
            - Path=/auth/**     

server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8083/eureka
