server:
  port: 8086 

spring:
  application:
    name: configServer
    
   

  cloud:
    config:
      server:
        git:
          uri: https://github.com/m4michael/microservConfig
          clone-on-start: true
          
          



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8083/eureka          